### ISSUE TITLE
Project (Protein) Editor

### ISSUE THREAD

**Issue by GoogleCodeExporter** [harlam357/hfm-net#138]
```
What enhancement are you proposing?

- Project (Protein) Editor

- Allow users to add Proteins that aren't available on the psummary... or
edit a Protein's information.

What version of the product are you using?

- 0.4.7.104
```

Original issue reported on code.google.com by `harlam357` on 29 Dec 2009 at 6:12

**Comment by harlam357** [comment]
With the project json feed now the default source for project information... I'm unsure if I'll pursue this.

**Comment by harlam357** [comment]
Closing... project json feed from Stanford has what everyone needs.
