### ISSUE TITLE
Transparent background in program icon

### ISSUE THREAD

**Issue by GoogleCodeExporter** [harlam357/hfm-net#294]
```
The program icon would be much nicer if the background were transparent, not 
black. The black border is especially visually distracting in the systray. 
In the past, I have hex-edited a transparent version of the icon into the 
program binaries. The icons are attached (each size separately and a combined 
icon).
```

Original issue reported on code.google.com by `martinbi...@gmail.com` on 19 Feb 2015 at 3:51

Attachments:
- [HFM.new.ico](https://storage.googleapis.com/google-code-attachments/hfm-net/issue-294/comment-0/HFM.new.ico)
- [HFM.new.48.ico](https://storage.googleapis.com/google-code-attachments/hfm-net/issue-294/comment-0/HFM.new.48.ico)
- [HFM.new.32.ico](https://storage.googleapis.com/google-code-attachments/hfm-net/issue-294/comment-0/HFM.new.32.ico)
- [HFM.new.16.ico](https://storage.googleapis.com/google-code-attachments/hfm-net/issue-294/comment-0/HFM.new.16.ico)

**Comment by harlam357** [comment]
Build 0.9.20.1222
