### ISSUE TITLE
Auto run on Windows Startup doesn't 

### ISSUE THREAD

**Issue by bb30994** [harlam357/hfm-net#299]
I have the "Auto Run on Startup" box checked but it doesn't actually happen when I reboot.

**Work-around:** I dropped a copy of the HFM shortcut into the Windows 7 Startup folder.

**Comment by harlam357** [comment]
Does anyone else have this issue?  I cannot reproduce.

**Comment by bb30994** [comment]
It's opening now.  I'm not sure what changed.
