### ISSUE TITLE
Incorrect status for slot 1+ when no work on slot 0

### ISSUE THREAD

**Issue by compwiz3688** [harlam357/hfm-net#303]
When slot 0 has no work unit assigned, other slots on the same client are not showing correct statuses (they do have work).

Please see attached below for computers named Mythbuntu and Ubuntu exhibiting this bug:
![HFM-bug-20200321](https://user-images.githubusercontent.com/59293368/77235609-cf422200-6b8d-11ea-8642-b698d1aceae4.png)
[HFM.log](https://github.com/harlam357/hfm-net/files/4363966/HFM.log)

**Comment by cshafer2** [comment]
I'm noticing this same issue on both of my Windows systems.  Slot 0 (CPU) has no work, but slot 1 (GPU) is folding

**Comment by Scefing** [comment]
Same issue, red squares highlight the same slots.
![2020-03-22 14_07_21-Window](https://user-images.githubusercontent.com/921547/77256806-d7aa6380-6c46-11ea-832d-2e8c291dc7de.png)

**Comment by harlam357** [comment]
Thanks for reporting this.  This has been an issue but the lack of work on the servers brought it out.  It is now fixed in 0.9.12.839.

**Comment by harlam357** [comment]
Fixed in v0.9.12.839
