### ISSUE TITLE
Better & new tooltips to explain things better

### ISSUE THREAD

**Issue by TunaErtemalp** [harlam357/hfm-net#309]
From our Google Groups thread: https://groups.google.com/d/msg/hfm-net/u_aJBM3DayI/ivBfzFWAAQAJ

**Suggestion:** Some acronyms used by FAH might be meaningful to old-timers, like PPD=PointsPerDay, but not to the new lot of 400,000. At least not readily. It would be awesome if the column titles would bring up a little tooltip to show a blurb about what they are for, when the cursor rests on them, and not just for the acronym columns but all. I find "TPF" as confusing as "Completed"/"Failed", the latter two being almost always 0/0 (therefore resulting in a "Huh?") and sometimes 2/0 or 1/0 (therefore resulting in a "What?"), all of which is not useful without knowing what they refer to, and probably very obvious once the user knows that meaning. Also for the status/stats data at the bottom right status bar. Tooltips on these would help. 

**Response:** I've had several others give me similar feedback regarding tooltips to explain things better.  I concur.

**Comment by harlam357** [comment]
Formalizing my response here:

- Tooltips for each column in the main graph.  I concur, a lot of value to add some additional detail here to help the newcomers.

- The status/stats data at the bottom right of the status bar.  I'd really like to move this data somewhere else in the UI.  The reason I refuse to expand the existing labels is simply due to horizontal space.  So in lieu of tooltips the new home will have spelled out labels that match those presented on EOC.

**Comment by harlam357** [comment]
Do you have any suggestions on what may be good tooltips, per column, for newcomers?

**Comment by TunaErtemalp** [comment]
I am a newbie, so this is probably only a partially accurate list. Please please please feel free to make them true and accurate. And, free of typos or English issues.

STATUS: "Slot status. Possible values: Ready, Sending, Running, Paused, ..., Finishing." (full list is something you know)

ETA: "Expected time of completion calculated based on the slot's progress so far"

TIMEOUT: "Date/Time when this slot is required to finish this workunit at the latest before considered too late" (by the way, looking at HFM and FAH Advanced Control for this, I realized in FAH there is TIMEOUT and EXPIRATION, and HFM has TIMEOUT. I don't know the difference between the two, and why you are not also showing EXPIRATION. The tooltip I proposed is actually for EXPIRATION, and I have no idea what TIMEOUT means)

CREDIT: "Credits expected to be earned by the completion of this workunit based on the progress so far" (correct?)

NAME: "Name of the host computer as you defined it, plus the slot number"

SLOT TYPE: "CPU:N where N is the number of CPU threads used by FAH, or GPU, plus version of FAH running on that host; latest FAH available on https://foldingathome.org/start-folding/ is X.Y.ZZ"

PPD: ""Points Per Day: dredits expected to be earned by this slot on a daily basis based on its performance so far. Use PPD Edit/Preferences/Options to affect the estimation." (correct? Or, "so far today"?)

CORE: "Engine plus engine iteration, and engine version being used by the workunit currently on this slot. GRO_* is for CPU slots, OPENMM_* is for GPU slots." (correct?)

Project (Run Clone, Gen): "???" (I have no idea except to know the "Project" id. The rest is unknown to me, and could use a tooltip to explain to me.

CoreID: "Engine iteration being used by the workunit currently on this slot. A7 is for CPU slots, 22 is for GPU slots." (Correct? Are A7 and 22 the only ones out there? If not, it should be a "... A5/A6/A7..." type of list.)

TPF: "???" (I have nooooo idea)

Completed: "Number of completed workunits on this slot since HFM.NET started tracking it (mm/dd/yyyy)."

Failed: "Number of failed workunits on this slot since HFM.NET started tracking it (mm/dd/yyyy). The last failure happened on mm/dd/yyyy."

Username: "Your FAH username and your TeamID" (it would be awesome if another tooltip could pop up while hovering on a cell value that said "Team nnn is [Team Name]". I think I might have another Issue added that suggests adding a TeamName column, but I am not sure as I am typing this."

Assigned: ""The timestamp when FAH assigned this workunit to this slot."

Regarding the status area, it would be great to have another area listing this data, but I also enjoy seeing it at the first glance. While you decide/implement, if you had the real estate, replacing Team & Project with "Rank in Team" and "Overall FAH Rank" would be very useful. Or, use these as tooltips on those two. And, consider bringing up the "N working slots, Y non working slots" tooltip when hovering over the "N slots" item, assuming turning if into at least "N of M slots" where M=N+Y.

**Comment by harlam357** [comment]
I had added some tooltips already before you shared this list and that code is in master.  I appreciate your efforts here and I'll certainly take your suggestions under advisement.  At first glance, some of them I find a bit lengthy and my goal is to keep them helpful, but concise.

For example, I the tooltip for TPF is "Time per frame (1% of progress)"

**Comment by TunaErtemalp** [comment]
Yeah, I tend to be... ...wordy. :) I tried to respond to your request for suggestions the next morning when everyone else at home was still asleep, so I had time to gab...

**Comment by harlam357** [comment]
I appreciate your efforts and engagement Tuna!

**Comment by harlam357** [comment]
Build 0.9.20.1230

I added additional tooltips everywhere there weren't any, except Core ID.  I'm planning on Core ID to be removed in the near future... it's redundant with the Core column.  Many years ago the Core value did not include the two character hex code (Core ID).  But that changed a long time ago.

Also, I was not verbose with the tooltips.  I feel like there are plenty of resources available (like foldingforum.org) where people can go to learn more about FAH and its terminology.
