### ISSUE TITLE
Possible new CPU/GPU columns with driver data

### ISSUE THREAD

**Issue by TunaErtemalp** [harlam357/hfm-net#314]
From our Google Groups thread: https://groups.google.com/d/msg/hfm-net/u_aJBM3DayI/ivBfzFWAAQAJ

**Suggestion:** In the Queue Viewer window, it would be awesome to have the "Driver" version as well as "Compute" level displayed, if it is a GPU slot. I see that data in the cached log file for each host/slot. This would be useful to see if all GPUs of certain kind are running the same latest driver etc.

**Response:** Driver and/or Compute version.  If I were to add a CPU / GPU column I think this version might be better there.  "Geforce RTX 2060 (432.0)" for example.  Can you expand on why Compute is a desirable value?  I can see driver version, but I'm not even sure what the Compute version represents

----

Compute is essentially the level of CUDA. The latest driver would have the latest Compute Level. Probably not too important to know for F@H since it seems to be using OpenCL and not CUDA.

**Comment by PantherX** [comment]
FYI, while GPU folding is currently using OpenCL, there are plans to support CUDA. Thus, whatever option is decided, it would need to support both, OpenCL and GUDA 😄

**Comment by harlam357** [comment]
Merging with Issue #341

**Comment by harlam357** [comment]
Closing with #341
