### ISSUE TITLE
Changing calculation settings in Preferences/Options should force a RefreshAll

### ISSUE THREAD

**Issue by TunaErtemalp** [harlam357/hfm-net#316]
Following your explanation of RunningNoFrameTimes in our Google Groups thread https://groups.google.com/d/msg/hfm-net/u_aJBM3DayI/ivBfzFWAAQAJ, I edited my Edit > Preferences > Options > Calculate PPD based on, and noticed that the change didn't get into effect until I did a Clients > Refresh All. I think **anything** that would change the way info in UI is displayed should cause a RefreshAll. Or, take the easy way out and force a RefreshAll while exiting this dialog when any changes have been made, to prevent future oversight of the effects of a new addition to this dialog.

**Comment by harlam357** [comment]
If you use Alt+P to cycle the different calculation types, you'll see HFM recalculates these values without executing a "Refresh All".  However, you are correct that this does not effect the "Running" vs "RunningNoFrameTimes" status.  I think I can push that decision outside of the client data refresh and make it dynamic like the other calculation changes.

Great observation!  The net effect will be what you're looking for, but without the need to execute a "Refresh All".
