### ISSUE TITLE
Better information about working/idle slots

### ISSUE THREAD

**Issue by TunaErtemalp** [harlam357/hfm-net#318]
From our Google Groups thread: https://groups.google.com/d/msg/hfm-net/u_aJBM3DayI/ivBfzFWAAQAJ

**Suggestion:** The lower right status area: instead of saying something like "9 slots", it could say some form of "9 of 14 (64%) slots" to give me a coarse idea of the busy/idle level of my slots.

**Response:** That represents the number of slots online.  If I move the EOC stats data from the status bar then I'd have more real estate to do something like your suggest.  If you look at HFM's system tray icon it does show "working" and "non-working" (perhaps "idle" would be a better word) slots in its tooltip.

**Comment by harlam357** [comment]
Build 0.9.20.1228
