### ISSUE TITLE
Some way to "restart" all waiting slots, manually or automatically

### ISSUE THREAD

**Issue by TunaErtemalp** [harlam357/hfm-net#327]
Due to the aggressive backoff strategy FAH uses, I routinely find myself doing PAUSE/FOLD on slots that have been in a wait period of a few hours, sometimes for an entire night. I understand the reasoning, namely not creating an accidental friendly fire DOS attack, but restarting that slot usually immediately gets a WU, so I still think that the FAH implementation of the backoff is too aggressive. And usually I end up doing those resets on multiple slots in one sitting. My previous "grid row multiselection" suggestion would definitely help. But what would REALLY help is a button or menu item that will just start looping over all currently idle slots, pause them, wait 5 seconds, unpause them. And even more awesome would be if the HFM could allow a Max slot wait period being entered by the user into Preferences so that during each scheduled client refresh, if it detects a slot waiting for longer than that user-set Max wait, it automatically does a pause/fold on that slot; setting the default of that to something like 60-90 minutes would both prevent accidental DOS attacks on FAH servers AND slots being idle for an entire night.

**Comment by braiam** [comment]
@TunaErtemalp the 7.6.11 version of the client reduced the maximum waiting time of one hour. That may make this FR obsolete?

**Comment by TunaErtemalp** [comment]
Oh, it definitely would put it at the bottom of the priority list! That is great news!

**Comment by TunaErtemalp** [comment]
I'll let @harlam357 close this, or decide to use it as a launchpad for some "automated management infrastructure" in HFM. I have no further requests in this particular application of what I was talking about.

**Comment by ipkh** [comment]
The limit was 6 hours max before the change to 1 hour.  So there was a limit, just a very long and dumb limit.  I'd also consider this as fixed by beta client.  Hasn't been released officially yet.

**Comment by TunaErtemalp** [comment]
7.6.13 is now released. I installed it on all my hosts. So far so good...
