### ISSUE TITLE
Exception in Benchmarks Viewer when not selecting an item in the ListBox

### ISSUE THREAD

**Issue by uyaem** [harlam357/hfm-net#328]
**Description**
When clicking in the ListBox on the left side of *Benchmarks Viewer*, in the "empty part" where no project IDs are listed, the following exception is thrown:

**Exception**
```
HFM.NET v0.9.17.1040

Microsoft Windows NT 6.2.9200.0

Exception Thrown:
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei HFM.Forms.BenchmarksForm.listBox1_SelectedIndexChanged(Object sender, EventArgs e)
   bei System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   bei System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   bei System.Windows.Forms.ListBox.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Steps to reproduce**
- Open Benchmarks Viewer
  - When no project ID is selected in the ListView, left- or right-click under the last item in the ListBox.
  - When a project ID is selected, only right-clicking causes it

Classic NPE, method `listBox1_SelectedIndexChanged` is missing a null check for `SelectedItem`.

**Comment by harlam357** [comment]
Nice find!  Fixed in master and available in next release.
