### ISSUE TITLE
Enhancement Idea: "Copy PCRG to Clipboard" in Context Menu

### ISSUE THREAD

**Issue by uyaem** [harlam357/hfm-net#329]
Would really be helpful in
- *Work Unit History* window
- *Main* window

Ideally in a format that can be pasted into https://apps.foldingathome.org/wu.
Thank you!

**Comment by harlam357** [comment]
Build 0.9.20.1225 includes Main Slots Grid

**Comment by harlam357** [comment]
Build 0.9.20.1227 includes WU History Grid
