### ISSUE TITLE
Slot PPD and Totals

### ISSUE THREAD

**Issue by SparklyIsHere** [harlam357/hfm-net#331]
I find it rather unlikely that several slots have the exact same PPD, to the decimal, so even thou it doesn’t update this more than every 1% the PPD should generally be slightly different.

Rock-001 Slot 1,2 and 5 + Rock-002 Slot 2 are exactly the same 328 983,9

![HFMPPD](https://user-images.githubusercontent.com/66365632/84944413-03be6f00-b0e6-11ea-95c1-49a4dc01c5cf.jpg)

The Totals also become somewhat different compared to the FAH Control, where you can also see that the Estimated PPD of Rock-001 Slot 1 is 324 417, whereas the HFM software shows it as 328 983,9

![HFMTotal](https://user-images.githubusercontent.com/66365632/84944454-146ee500-b0e6-11ea-86ab-b6be31aa9bf4.jpg)

**Comment by uyaem** [comment]
I can at least explain the difference in numbers between HFM and FAHControl...

Unless you changed the default settings, HFM will average over the last three frames. You can switch this to other averages, or even just the last frame via **Edit --> Preferences**, tab **Options**, drop-down **Calculate PPD based on** in top right-hand corner.

FAHControl has a mind of its own and recalculates constantly, even mid-frame. Not sure about the logic there.

**Comment by SparklyIsHere** [comment]
Okies, thanks, changed the default to ”All Frames” and the same project now shows the variations I would expect to see, as can be seen on the Rock-001 that is currently running 5 instances of the same project 16435.

![AllFrames](https://user-images.githubusercontent.com/66365632/85226150-475ef480-b3d6-11ea-8843-c62aa77f38b4.jpg)

**Comment by harlam357** [comment]
I concur with this statement: _FAHControl has a mind of its own and recalculates constantly, even mid-frame._

Glad you got it figured out. :-)  Yes, HFM uses an observed approach vs. the predictive approach of FAHControl.
