### ISSUE TITLE
Core v0.0.10 displays as 0.1

### ISSUE THREAD

**Issue by rhavern** [harlam357/hfm-net#332]
When the openmm_22 core got incremented to v0.0.10, hfm appears to truncate the version to 0.1 instead of the expected 0.10; using hfm v0.9.17

**Comment by PantherX** [comment]
Just wondering if this impacts only the data view or the actual data. In other words, is the stored data 0.10 or has it been lost and only 0.1 is stored.
Reason is if it is a data view issue, then fixing the viewer will resolve it. If it is a data source issue, then maybe some kind of manual fix which users can run to ensure that the data is correctly stored.

**Comment by harlam357** [comment]
It's stored in the work unit history as a numeric, decimal value.  I stated it somewhere, probably slack, not too long ago.  Bad decision from many, many years ago.  Back in the FAH v5 and v6 days, core versions were major.minor and that's it.  So a decimal number worked fine.  Obviously, things have changed.

I plan to do something about this.  I can fix what is displayed on screen with the in progress work units easily enough... but fixing existing entries in the work unit history is not something I plan to attempt.  I'd rather keep the existing data than guess at what the version should be.  I have plans to completely rework the data storage for work unit history and benchmarks and this will be addressed in the persisted data at that point.

**Comment by PantherX** [comment]
Yep, that's understandable and look forward to the new structure whenever it's ready 😄

**Comment by harlam357** [comment]
0.9.22 fixed display of core version in the UI.
