### ISSUE TITLE
Digit Grouping, Y-axis Alignment, & X-axis Text Direction

### ISSUE THREAD

**Issue by PantherX** [harlam357/hfm-net#336]
## Is your feature request related to a problem?

Not really... it could be considered a viewing problem but that's it. Functionally, it works as expected. Thank you very much for the new feature 😄 

----
## Describe the Feature

I would like it if digit grouping is implemented on the Y-axis. While I am partial to a , for grouping, there are [other methods](https://en.wikipedia.org/wiki/Decimal_separator#Current_standards) too.

It would be nice if the Y-axis is right justified. That way, if you were to use digit grouping, it would be very easy to differentiate between values.

It would be nice if the text was rotated by 45 degrees so that each interval can have the corresponding project number printed without making it too hard to read. [Demo image](https://excelnotes.com/wp-content/uploads/2019/12/excelwrapxaxis005.jpg).

----
## Context

When comparing a handful of Projects, it is easy. However, when comparing many projects, it makes a difference as shown below for my system:
![image](https://user-images.githubusercontent.com/5349122/91644664-5c20ce00-ea92-11ea-883c-4edeee1d42fc.png)

I do understand that you have plans for better data representation in future so this could be something that you can think about when you get there.

----

**Comment by harlam357** [comment]
Regarding Y-Axis, the default behavior looks like this.  You can actually make it do this yourself if you right click the graph and select "Set Scale to Default".  I don't like that view, but it's an option.

![image](https://user-images.githubusercontent.com/13512136/91647698-41634080-ea23-11ea-9547-b40a5b413190.png)

I do not generate these PPD labels, the graphing control does it based on the given input.

Regarding the X-Axis, I agree it would be nice if each and every project was listed but I've found no way to make that happen.  In general, if you want to see all X-Axis "ticks" with a label, then select fewer projects.  Again, at the mercy of what the graphing control generates.

FWIW, this graphing control is an older freebie.  Based on my research there are better, paid options out there.  But this is an OSS project and I'm not going to shell out $$$ for it, nor would I want anyone else to do so.

Here's a link to an article that "shows off" what it can do if you're interested: https://www.codeproject.com/Articles/5431/A-flexible-charting-library-for-NET

**Comment by PantherX** [comment]
Ah, yep, the Y-axis workaround is good enough that I don't read 1000000 and 100000 as same so that's easy enough for me!

Oh, I didn't know the limitations on newer graphing software 😞 Thanks for the link, will view it and see what appeals to me 😄

**Comment by harlam357** [comment]
Yeah, just pointing out that there are other options out there, but the options I've found cost $$$.  I haven't evaluated them to see if they would be capable of "fixing" what you're asking for.  I'm pleased enough with what ZedGraph brings to the table.  If anyone knows of a nice WinForms graphing control that is free and has more control, I'm all ears.

I appreciate the feedback Panther!  I'm closing this as 'wontfix'.
