### ISSUE TITLE
Add CPU/GPU device description in console & WU history

### ISSUE THREAD

**Issue by atlbike** [harlam357/hfm-net#338]
Request as described in a previous response:  Response: Driver and/or Compute version. If I were to add a CPU / GPU column I think this version might be better there. "Geforce RTX 2060 (432.0)" for example. Like the FAHcontrol client.
I'm having difficulty determining which GPUtype correlates to a name/slot designation for performance comparison.  Then if GPUs are shuffled for testing various OS, PCIE slot speed, the historical data loses any correlation to the device type.

**Comment by Gnomuz** [comment]
I fully agree with this feature request, as I happen to hire GPUs on vast.ai when the prices are acceptable. After a while it's impossible to remember which GPU was at work so the WU history doesn't make much sense, with an RTX 3080 and a GTX1080Ti appearing under the same client/slot name ...
On top of the driver version as suggested by atlbike, I would also appreciate if the running OS were stored in the WU history, as it would allow for performance comparison after a kernel and/or distro upgrade.
Thanks in advance, and let's keep folding anyway !

**Comment by harlam357** [comment]
Closing as completed with the v10.0 release
