### ISSUE TITLE
Work Unit History should store, display and export WU Base Credit

### ISSUE THREAD

**Issue by rhavern** [harlam357/hfm-net#347]
Currently Timeout and Expiration Days are stored but not Base Credit.  Thanks.

**Comment by harlam357** [comment]
The exported credit value should be based on the selection in the UI.  Because I know the bonus values are calculated on the fly based on the WU information captured with each completed WU.

**Comment by rhavern** [comment]
I'm not referring to the awarded credit, I'm talking about the Base Credit.  This is visibile in Benchmarks Viewer as Credit.  BC is set by the researcher, awarded credit is calculated based on this and time to complete.

    On Thursday, 6 May 2021, 11:56:38 BST, Ryan Harlamert ***@***.***> wrote:  
 
 


The exported credit value should be based on the selection in the UI. Because I know the bonus values are calculated on the fly based on the WU information captured with each completed WU.

**Comment by harlam357** [comment]
Before I close this Rick... I just double checked, the base credit is stored in the database.  You are correct that the export will not output base and selected bonus credit at the same time.  I can do that pretty easily if you'd like.  Sorry for taking so long to get back to this issue.

**Comment by rhavern** [comment]
Yes please!
Thanks.

    On Saturday, 28 August 2021, 04:37:47 BST, Ryan Harlamert ***@***.***> wrote:  
 
 


Before I close this Rick... I just double checked, the base credit is stored in the database. You are correct that the export will not output base and selected bonus credit at the same time. I can do that pretty easily if you'd like. Sorry for taking so long to get back to this issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
