### ISSUE TITLE
Username validation check

### ISSUE THREAD

**Issue by walderston** [harlam357/hfm-net#352]
Looks like the FAH donor status page has been updated and you need to supply your donor ID rather than username..

i.e. it needs to be: https://stats.foldingathome.org/donor/111111 and not https://stats.foldingathome.org/donor/username

In preferences when I update the 'FAH User ID' from the username to the ID, I get an error saying 'Client's username does not match the username configured in HFM preferences.'

**Comment by harlam357** [comment]
Thanks for the heads up.  I'll have to look into the FAH APIs and see if there's a way for me to lookup the ID number based on the name or vice-versa.

**Comment by firedfly** [comment]
@harlam357 
This api should work to retrieve the userID:  https://api2.foldingathome.org/user/firedfly
Documentation is here: https://api2.foldingathome.org/#GET-/user/:name
