### ISSUE TITLE
Suggestion - Timeout in time instead of date

### ISSUE THREAD

**Issue by hucker75** [harlam357/hfm-net#357]
It's currently possible to display ETA in time or as a date.  But I can't change the timeout column like this.  I would like both the same so I can easily see if something will complete on time, but times are easier than dates as I don't have to work out when that will be.

**Comment by harlam357** [comment]
Select View > Toggle Date/Time Style to see those values like this.

![image](https://user-images.githubusercontent.com/13512136/230702637-f0e7231c-3f73-4a2e-b294-39dad326cd90.png)
