### ISSUE TITLE
High resolution scaling issues

### ISSUE THREAD

**Issue by harlam357** [harlam357/hfm-net#358]
Something changed between v9.28.1718 and the major v10 update

![image](https://user-images.githubusercontent.com/13512136/169663779-05fc2371-06ef-4cfc-b9f2-d9da56a7d49e.png)

![image](https://user-images.githubusercontent.com/13512136/169663788-4dc056d6-853c-49b1-b243-08d6f66285f3.png)

**Comment by Justaphf** [comment]
The following line worked for me for the main display. I'm on a 4K monitor with 150% scaling.
![image](https://user-images.githubusercontent.com/6402604/178157936-de9ed7fe-b7c5-411e-853c-dfcf0098e31d.png)

Before:
![image](https://user-images.githubusercontent.com/6402604/178157987-488b2636-66d7-43df-a049-f4a33e591575.png)

After:
![image](https://user-images.githubusercontent.com/6402604/178157965-5ef9d7af-b59a-4dc9-8368-e136b9280201.png)
