### ISSUE TITLE
Core23 v8.0.3 log not correctly interpreted correctly by HFM

### ISSUE THREAD

**Issue by rhavern** [harlam357/hfm-net#368]
This version of core23 is a likely release candidate.  Attached is my log from Ubuntu 22.04.  Do you need a windows log as well?

There is an OpenCL WU followed by a CUDA WU in the log.

[20230805 v803 log.txt](https://github.com/harlam357/hfm-net/files/12266863/20230805.v803.log.txt)

**Comment by rhavern** [comment]
Core 23 is just about to be released into the wild with the first projects to use it, so this issue is getting more critical.

**Comment by rhavern** [comment]
Core 23 is now being actively used by researchers.

**Comment by harlam357** [comment]
I've got the fix in the works. Everything appears to work fine except the platform (CUDA, OpenCL) detection.
